### ISSUE TITLE
How usable is this? Could you provide more examples?

### ISSUE THREAD

**Issue by Ashe** [longlene/cl-raylib#2]
Hey there,

I'm very interested in using raylib + common lisp, however your example isn't really enough of an introduction to a beginner when paired with (the lack of) documentation. I really want to use your project, but I'm a little bit stuck.

Could you perhaps show a very simple 3D example just to show that it's functional and as a demonstration of how it will work? [There are plenty of examples on Raylib's website](https://www.raylib.com/examples.html) that you could port over - I can see that most of the functions have the same names but I'm struggling to understand how to use them (particularly, creating a camera for beginning a 3D game).

I would love to use your library and even help out if I learn a bit more, because raylib is an awesome library and lisp is an awesome language!

**Comment by longlene** [comment]
Sorry for late response, will try to port some examples.

**Comment by Ashe** [comment]
Thank you so much! I look forward to seeing how these bindings are used and how complete they are! I suspected they are complete but I just couldn't figure out how to use them, but that's partly because I'm a little new to FFI stuff.

**Comment by olegharput** [comment]
i am trying to port those examples, but i need help, if you want to help me, just answer my questions please.
Check the issues part please.

**Comment by longlene** [comment]
It's ok, just post your questions.
