### ISSUE TITLE
Camera first person and third person constants are not defined correctly in raylib.lisp

### ISSUE THREAD

**Issue by ragnargisli** [longlene/cl-raylib#20]
Those 2 constants are defined with underscore but exported with dash, see below:

line 1850 in raylib.lisp
```
(define-constant +camera-first_person+ 3)
(define-constant +camera-third_person+ 4)
```

line 210 in package.lisp
```
    #:+camera-first-person+
    #:+camera-third-person+
```

**Comment by longlene** [comment]
@ragnargisli Thank you, good catch! I'll correct it later.

**Comment by longlene** [comment]
https://github.com/longlene/cl-raylib/commit/da0eb03cef49f7a4dabd83d771e4a5d7ed0a9e74 fixed in this commit
