### ISSUE TITLE
Update raylib's BINDINGS.md file

### ISSUE THREAD

**Issue by tupini07** [longlene/cl-raylib#21]
This library appears in Raylib's [BINDINGS.md](https://github.com/raysan5/raylib/blob/master/BINDINGS.md) file, but the file shows it in the `Older or Unmaintained Language Bindings` section, saying that the supported version is 3.0.

Would it be correct to update the BINDINGS file so that _cl-raylib_ appears as a maintained project as well as that it supports version 4.0?

**Comment by longlene** [comment]
@tupini07 Thank you for the info, it support 4.0 now, maybe I can submit a issue there.

**Comment by longlene** [comment]
Since it's updated already, I'll close the issue now.
