### ISSUE TITLE
`load-render-texture` causes a type error about `SB-SYS:SYSTEM-AREA-POINTER`

### ISSUE THREAD

**Issue by sushi-buffer** [longlene/cl-raylib#24]
When attempting to invoke `(load-render-texture 100 100)` the spirits from within this library sing these omenous messages:

```
The value
  #S(CL-RAYLIB::TEXTURE
     :ID 3
     :WIDTH 100
     :HEIGHT 100
     :MIPMAPS 1
     :FORMAT 7)

is not of type
  SB-SYS:SYSTEM-AREA-POINTER
   [Condition of type TYPE-ERROR]
```

Could this, perhaps, be related to [10](https://github.com/longlene/cl-raylib/issues/7)?

**Comment by longlene** [comment]
Hi, @4lph4-Ph4un Thank you for the finding and sorry for the late response.

I did some tests and reproduced it.

Now I just fixed this issue: https://github.com/longlene/cl-raylib/commit/bf7365afe4cab073c7f185128a33a6adfc45655f

**Comment by ghost** [comment]
Whoa, no but that was actually pretty fast! 😄 Thank YOU!!! 💯
I'm fairly new to this library but I intend to play around and study the ins and outs of it, so I'll report if I find anything else!

**Comment by ghost** [comment]
Just tested and works perfectly! Thanks again! 👍
