### ISSUE TITLE
Supporting Vector and Matrix operations

### ISSUE THREAD

**Issue by kiran-kp** [longlene/cl-raylib#25]
Would you be open to integrating [Shinmera/3d-vectors](https://github.com/Shinmera/3d-vectors) and [Shinmera/3d-matrices](https://github.com/Shinmera/3d-matrices)? The alternative is to implement all the required operations in this library but that seems unnecessary.

If you're open to this, I can submit a pull request with the required changes.

**Comment by longlene** [comment]
@kiran-kp Thank you! Let me have a test at first
