### ISSUE TITLE
core_world_screen example fails to place text correctly

### ISSUE THREAD

**Issue by stacksmith** [longlene/cl-raylib#28]
Ubuntu 20.04.4 LTS x86_64
5.4.0-122-generic
SBCL 2.2.6

The text in the example states 'text is always on top of the cube', and the C example keeps text on top of cube.

The cl example code fails to do so.  The x position of text is always the same.

 ̶I̶ ̶j̶u̶s̶t̶ ̶s̶t̶a̶r̶t̶e̶d̶ ̶l̶o̶o̶k̶i̶n̶g̶ ̶a̶t̶ ̶r̶a̶y̶l̶i̶b̶ ̶a̶n̶d̶ ̶c̶l̶-̶r̶a̶y̶l̶i̶b̶,̶ ̶a̶n̶d̶ ̶c̶a̶n̶'̶t̶ ̶t̶e̶l̶l̶ ̶w̶h̶y̶ ̶t̶h̶i̶s̶ ̶i̶s̶ ̶h̶a̶p̶p̶e̶n̶i̶n̶g̶.̶

**Comment by stacksmith** [comment]
fixed in PR #30

**Comment by longlene** [comment]
Merged, thank you!
