### ISSUE TITLE
Can someone find the reasons of the error in this code?

### ISSUE THREAD

**Issue by olegharput** [longlene/cl-raylib#7]
(defparameter +max-frame-speed+ 15)
(defparameter +min-frame-speed+ 1)

(defun main ()
  (let* ((screen-width 800)
	 (screen-height 450)
	 (scarfy (loadtexture "/home/huseyin/quicklisp/local-projects/game15/assets/textures_rectangle.png"))
	 (position (make-vector2 :x 350.0 :y 280.0))
	 (frame-rec (make-rectangle :x 0.0
				    :y 0.0
				    :width (/ (texture-width scarfy) 6.0)
				    :height (* (texture-height scarfy) 1.0)))
	 (current-frame 0)
	 (frames-counter 0)
	 (frames-speed 8))
    (unwind-protect
	 (progn (r:set-target-fps 60)
		(loop
		  :do
		     (incf frames-counter)
		     (if (> frames-counter (/ 60 frames-speed))
			 (progn (setf frames-counter 0)
				(incf current-frame)
				(when (> current-frame 5)
				  (setf current-frame 0))
				(setf (rectangle-x frame-rec)
				      (* (* 1.0 current-frame)
					 (/ (texture-width scarfy) 6.0)))))
		     (cond ((r:is-key-pressed +key-right+) (incf frames-speed))
			   ((r:is-key-pressed +key-left+) (decf frames-speed)))
		     (cond ((> frames-speed +max-frame-speed+) (setf frames-speed +max-frame-speed+))
			   ((< frames-speed +min-frame-speed+) (setf frames-speed +min-frame-speed+)))
		     (r:begin-drawing)
		     (r:clear-background r:+raywhite+)
		     (r:draw-texture scarfy 15 40 r:+white+)
		     (r:draw-rectangle-lines 15 40 (texture-width scarfy) (texture-height scarfy) r:+lime+)
		     (r:draw-rectangle-lines (+ 15 (rectangle-x frame-rec))
					     (+ 40 (rectangle-y frame-rec))
					     (rectangle-width frame-rec)
					     (rectangle-height frame-rec)
					     r:+lime+)
=> "Unhandled memory fault at #x0."

[rectangle.zip](https://github.com/longlene/cl-raylib/files/5524690/rectangle.zip)

**Comment by compufox** [comment]
I'm going off of your code from the included rectangle.zip file,
but a texture can only be instantiated after a window is created.

in both the example you have here and in rectangle.lisp you don't open a window context. this would also mean that your `unwind-protect` clause at the end wouldn't be able to unload the texture so i threw that into the main loop as well.

here's the full code I got to work

```lisp
(ql:quickload :cl-raylib)
(defpackage :game15
  (:use :cl :raylib)
  (:local-nicknames (:r :cl-raylib)))
(in-package #:game15)

(defparameter +max-frame-speed+ 15)
(defparameter +min-frame-speed+ 1)

(defun main ()
  (let* ((screen-width 800)
	 (screen-height 450)
	 (position (make-vector2 :x 350.0 :y 280.0))
	 (current-frame 0)
	 (frames-counter 0)
	 (frames-speed 8))
    (with-window (screen-width screen-height "raylib test")
      (let* ((scarfy (load-texture "rectangle.png"))
             (frame-rec (make-rectangle :x 0.0
                                        :y 0.0
                                        :width (/ (texture-width scarfy) 6.0)
                                        :height (* (texture-height scarfy) 1.0))))
        (r:set-target-fps 60)
        (loop
          :do
             (incf frames-counter)
             (if (> frames-counter (/ 60 frames-speed))
                 (progn (setf frames-counter 0)
                        (incf current-frame)
                        (when (> current-frame 5)
                          (setf current-frame 0))
                        (setf (rectangle-x frame-rec)
                              (* (* 1.0 current-frame)
                                 (/ (texture-width scarfy) 6.0)))))
             (cond ((r:is-key-pressed +key-right+) (incf frames-speed))
                   ((r:is-key-pressed +key-left+) (decf frames-speed)))
             (cond ((> frames-speed +max-frame-speed+) (setf frames-speed +max-frame-speed+))
                   ((< frames-speed +min-frame-speed+) (setf frames-speed +min-frame-speed+)))
             (r:begin-drawing)
             (r:clear-background r:+raywhite+)
             (r:draw-texture scarfy 15 40 r:+white+)
             (r:draw-rectangle-lines 15 40 (texture-width scarfy) (texture-height scarfy) r:+lime+)
             (r:draw-rectangle-lines-ex frame-rec 1 r:+lime+)
             
             (r:draw-text "FRAME SPEED: " 165 210 10 r:+darkgray+)
             (r:draw-text (r:text-format (format nil "%02~A FPS" frames-speed)) 575 210 10 r:+darkgray+)
             (r:draw-text "PRESS RIGHT/LEFT KEYS to CHANGE SPEED!" 290 240 10 r:+darkgray+)
             (do ((i 0 (1+ i)))
                 ((= i (- +max-frame-speed+ 1)))
               (when (< i frames-speed)
                 (r:draw-rectangle (+ 250 (* 21 i)) 205 20 20 r:+red+)
                 (r:draw-rectangle-lines (+ 250 (* 21 i)) 205 20 20 r:+maroon+)))
             (r:draw-texture-rec scarfy frame-rec position r:+white+)
             (r:draw-text "(c) Scarfy sprite by Eiden Marsal" (- screen-width 200) (- screen-height 20) 10 r:+gray+)
             (r:end-drawing)
          :until (r:window-should-close)
          :finally (unload-texture scarfy))))))
```
