### ISSUE TITLE
I can not fix the problem between (print "bbbbbbb) and (print "cccccccc") in example 'camera.lisp', need help.

### ISSUE THREAD

**Issue by olegharput** [longlene/cl-raylib#8]
(defun camera ()
     (let* ((screen-width 800)
         (screen-height 450)
         (title "raylib [core] example - 3d camera mode")
         (camera-pos (make-vector3 :x 0.0 :y 10.0 :z 10.0))
         (camera-target (make-vector3 :x 0.0 :y 0.0 :z 0.0))
         (camera-up (make-vector3 :x 0.0 :y 1.0 :z 0.0))
         (camera (make-camera3d :position camera-pos :target camera-target :up camera-up :fovy 45.0 :type +camera-perspective+))
         (cube-pos (make-vector3 :x 0.0 :y 0.0 :z 0.0)))
    (with-window (screen-width screen-height title)
      (set-target-fps 60) ; Set our game to run at 60 FPS
      (print "aaaaaaaaaa")
      (loop
	(if (window-should-close) (return)) ; dectect window close button or ESC key
	(with-drawing
	  (clear-background +raywhite+)
	  (let* ((aaa (camera3d-position camera))
		 (bbb (camera3d-target camera))
		 (ccc (camera3d-up camera))
		 (ddd (camera3d-fovy camera))
		 (eee (camera3d-type camera))
		 (lll (list aaa bbb ccc ddd eee)))
		 (print "bbbbbbbbbbbbbb")
		 (with-mode-3d (lll)
		   (print "cccccccccccccc")
		   (draw-cube cube-pos 2.0 2.0 2.0 +red+)
		   (print "ddddddddddddddd")
		   (draw-cube-wires cube-pos 2.0 2.0 2.0 +maroon+)
		   (print "eeeeeeeeeeee")
		   (draw-grid 10 1.0))
		 (draw-text "Welcome to the third dimension!" 10 40 20 +darkgray+)
		 (draw-fps 10 10))))))))

    ;; -----------------------------------------------------------------------------------
    (defcstruct (%vector3 :class vector3-type)
     "Vector3 type"
     (x :float)
     (y :float)
     (z :float))

    (defstruct vector3
     x y z)

    (defmethod translate-into-foreign-memory (object (type vector3-type) pointer)
      (with-foreign-slots ((x y z) pointer (:struct %vector3))
                      (setf x (vector3-x object))
                      (setf y (vector3-y object))
                      (setf z (vector3-z object))))

    (defmethod translate-from-foreign (pointer (type vector3-type))
      (with-foreign-slots ((x y z) pointer (:struct %vector3))
                      (make-vector3 :x x :y y :z z)))

    (defcstruct (%camera3d :class camera3d-type)
     "Camera type, defines a camera position/orientation in 3d space"
     (position (:struct %vector3))
     (target (:struct %vector3))
     (up (:struct %vector3))
     (fovy :float)
     (type :int))
        ;; -----------------------------------------------------------------------------------
    (defstruct camera3d
      position target up fovy type)

     (defmethod translate-into-foreign-memory (object (type camera3d-type) pointer)
      (with-foreign-slots ((fovy type) pointer (:struct %camera3d))
                      (convert-into-foreign-memory (camera3d-position object) '(:struct %vector3) 
    (foreign-slot-pointer pointer '(:struct %camera3d) 'position))
                      (convert-into-foreign-memory (camera3d-target object) '(:struct %vector3) (foreign- 
     slot-pointer pointer '(:struct %camera3d) 'target))
                      (convert-into-foreign-memory (camera3d-up object) '(:struct %vector3) (foreign- 
     slot-pointer pointer '(:struct %camera3d) 'up))
                      (setf fovy (camera3d-fovy object)
                            type (camera3d-type object))))

    (defmethod translate-from-foreign (pointer (type camera3d-type))
      (with-foreign-slots ((position target up fovy type) pointer (:struct %camera3d))
                      (let ((px (foreign-slot-value position '(:struct %vector3) 'x))
                            (py (foreign-slot-value position '(:struct %vector3) 'y))
                            (pz (foreign-slot-value position '(:struct %vector3) 'z))
                            (tx (foreign-slot-value target '(:struct %vector3) 'x))
                            (ty (foreign-slot-value target '(:struct %vector3) 'y))
                            (tz (foreign-slot-value target '(:struct %vector3) 'z))
                            (ux (foreign-slot-value up '(:struct %vector3) 'x))
                            (uy (foreign-slot-value up '(:struct %vector3) 'y))
                            (uz (foreign-slot-value up '(:struct %vector3) 'z)))
                        (make-camera3d :position (make-vector3 :x px :y py :z pz)
                                       :target (make-vector3 :x tx :y ty :z tz)
                                       :up (make-vector3 :x ux :y uy :z uz)
                                       :fovy fovy
                                       :type type))))

    (defmacro with-mode-3d ((camera) &body body)
     `(progn (begin-mode-3d ,camera)
         (unwind-protect (progn ,@body)
          (end-mode-3d))))
        ;; -----------------------------------------------------------------------------------
    (define-constant +camera-perspective+ 0)

    ;;i have ccopied them from https://github.com/compufox/cl-raylib/blob/missing- 
    functions/src/raylib.lisp

**Comment by compufox** [comment]
i think if you change `(with-mode-3d (lll)` to `(with-mode-3d (camera)` it should work.

a few side notes:
- now that my changes were merged into the master branch here you should probably be using it instead of my version
- you may also want to close any issues that you've opened that are resolved


full code that i got to work
```lisp
(defun camera ()
 (let* ((screen-width 800)
        (screen-height 450)
        (title "raylib [core] example - 3d camera mode")
        (camera-pos (make-vector3 :x 0.0 :y 10.0 :z 10.0))
        (camera-target (make-vector3 :x 0.0 :y 0.0 :z 0.0))
        (camera-up (make-vector3 :x 0.0 :y 1.0 :z 0.0))
        (camera (make-camera3d :position camera-pos :target camera-target :up camera-up :fovy 45.0 :type +camera-perspective+))
        (cube-pos (make-vector3 :x 0.0 :y 0.0 :z 0.0)))
   (with-window (screen-width screen-height title)
     (set-target-fps 60) ; Set our game to run at 60 FPS
     (print "aaaaaaaaaa")
     (loop
       (if (window-should-close) (return)) ; dectect window close button or ESC key
       (with-drawing
         (clear-background +raywhite+)
         (let* ((aaa (camera3d-position camera))
                (bbb (camera3d-target camera))
                (ccc (camera3d-up camera))
                (ddd (camera3d-fovy camera))
                (eee (camera3d-type camera))
                (lll (list aaa bbb ccc ddd eee)))
           (print "bbbbbbbbbbbbbb")
           (with-mode-3d (camera)
             (print "cccccccccccccc")
             (draw-cube cube-pos 2.0 2.0 2.0 +red+)
             (print "ddddddddddddddd")
             (draw-cube-wires cube-pos 2.0 2.0 2.0 +maroon+)
             (print "eeeeeeeeeeee")
             (draw-grid 10 1.0))
           (draw-text "Welcome to the third dimension!" 10 40 20 +darkgray+)
           (draw-fps 10 10)))))))
```
